name: "NowSecure"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - uses: gradle/gradle-build-action@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build application
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./app/k9mail/build/outputs/apk/debug/k9mail-debug.apk
          retention-days: 3

  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download application
        uses: actions/download-artifact@v4.1.7
        with:
          name: app

      - id: upload
        name: NowSecure upload app
        uses: nowsecure/nowsecure-action/upload-app@v3
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          app_file:  "k9mail-debug.apk"	
          group_id: "2f54e472-2487-45a4-81b0-ceeb71c548ac"	 
          
  process:
    if: ${{ needs.scan.outputs.report_id }}
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 30
        with:
          report_id: ${{ needs.scan.outputs.report_id }}
          platform_token: ${{ secrets.NS_TOKEN }}
          group_id: "2f54e472-2487-45a4-81b0-ceeb71c548ac"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: NowSecure.sarif
    
