name: "NowSecure SBOM"

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - uses: gradle/gradle-build-action@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build application
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./app/k9mail/build/outputs/apk/debug/k9mail-debug.apk
          retention-days: 3
  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download application
        uses: actions/download-artifact@v2
        with:
          name: app
          
      - name: NowSecure upload app
        uses: nowsecure/nowsecure-sbom-action@v2
        timeout-minutes: 30
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          app_file: "k9mail-debug.apk"	
          group_id: "2f54e472-2487-45a4-81b0-ceeb71c548ac"
  
